// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrtbrmepxgojczkrpulh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydGJybWVweGdvamN6a3JwdWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjAyNjAsImV4cCI6MjA2MDgzNjI2MH0.g40uPFS9iqwlvIYejXun4H4K4-0gJxMtEjH0QpFXEi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);